name: Version or Publish

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          git config --global user.name 'leonschiphol'
          git config --global user.email 'leon.vosmeijer@schiphol.nl'

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: ./
        with:
          version: yarn bump
          publish: yarn release
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
